-- Migration: expand thin categories (pilot) — Restructuring + Capital Markets
-- Date: 2026-06-24
--
-- The level audit (2026_17..19) surfaced that Restructuring and Capital Markets
-- each held only 6 primary questions — indefensibly thin for full IB interview
-- tracks. This pilot adds 12 primary questions (6 each), authored around the
-- existing 1556-1567 set to avoid topic overlap, spread across levels with
-- difficulty kept inside each level's selector band (intern 1-3, analyst 2-4,
-- associate 3-5). IDs continue from max(id)=1571.
--
-- Shape matches the bank: type='primary', parent_id=NULL, region='Global',
-- 5-7 key_points rubric items, ~1000-char first-person model_answer.

insert into public.questions
  (id, parent_id, type, category, subtopic, importance, difficulty, candidate_level, region, question, key_points, model_answer)
values
-- ============================== Restructuring ==============================
(1572, NULL, 'primary', 'Restructuring', 'Chapter 11 Process', 'core', 3, 'analyst', 'Global',
 $q$Walk me through what actually happens when a company files for Chapter 11 — the automatic stay, DIP financing, and the path to a plan.$q$,
 $kp$["Filing triggers the automatic stay: collections, lawsuits, and foreclosures freeze immediately","Company runs as debtor-in-possession under court oversight, not a trustee","DIP financing funds operations with super-priority and often priming liens","First-day motions keep the lights on: payroll, critical vendors, cash collateral","Reorganization runs through a plan: classify claims, negotiate, solicit votes","Plan needs requisite votes plus court confirmation; cramdown binds dissenting classes","Exit via a confirmed plan of reorganization or a 363 asset sale"]$kp$::jsonb,
 $ma$When a company files Chapter 11, the automatic stay kicks in immediately — all collection efforts, lawsuits, and foreclosures freeze, which gives the company breathing room. Management usually stays in control as the debtor-in-possession, running the business under court oversight rather than handing it to a trustee. Because a filing scares off normal lenders, the company arranges DIP financing — debtor-in-possession loans that carry super-priority and often prime existing liens, which is exactly why a lender will fund a bankrupt borrower. On day one, first-day motions keep the company operating: paying employees, critical vendors, and using cash collateral. From there the goal is a plan of reorganization — you classify claims by seniority, negotiate recoveries with each class, and solicit votes. The plan needs the required creditor votes plus court confirmation, and if a class objects the company can try to cram down a plan that's fair and feasible. The company ultimately exits through that confirmed plan or by selling its assets in a 363 sale.$ma$),

(1573, NULL, 'primary', 'Restructuring', 'DIP Financing', 'core', 3, 'analyst', 'Global',
 $q$What is DIP financing, and why is a lender willing to fund a company that just filed for bankruptcy?$q$,
 $kp$["DIP financing is new money lent to a company already in Chapter 11","Requires court approval; lender gets a super-priority administrative claim","Often secured by priming liens ahead of existing secured debt","Tight controls: budget, milestones, covenants, sometimes a roll-up of pre-petition debt","Gives the company liquidity to operate and signals viability to counterparties","Low real risk for the lender despite distress: priority, collateral, court-supervised budget"]$kp$::jsonb,
 $ma$DIP financing is debtor-in-possession financing — new money lent to a company after it files Chapter 11. The reason a lender will fund a borrower that just defaulted comes down to priority and control. A DIP loan must be approved by the bankruptcy court, and in exchange the lender gets a super-priority claim ahead of essentially all other unsecured and administrative claims. It's often secured by priming liens that leapfrog even existing secured lenders, so the DIP lender sits first on the collateral. On top of that, DIP facilities carry tight controls — an agreed budget, milestones, covenants, and sometimes a roll-up of pre-petition debt. So even though the company is distressed, the lender's real risk is low: they're first-priority, well-collateralized, and watching a court-supervised budget. For the company, the DIP provides the liquidity to keep operating through the case and signals to vendors and customers that it can fund itself all the way to a plan.$ma$),

(1574, NULL, 'primary', 'Restructuring', 'Fulcrum Security', 'advanced', 4, 'analyst', 'Global',
 $q$What is the fulcrum security, and how do you figure out which part of the capital structure it is?$q$,
 $kp$["Most senior claim that is not repaid in full in the restructuring","The layer where enterprise value runs out and breaks","Senior claims are money-good at par; junior claims are out of the money","Typically converts into the new equity of the reorganized company","Found by waterfalling enterprise value down the structure by priority","Distressed funds buy the fulcrum to convert debt into ownership and control"]$kp$::jsonb,
 $ma$The fulcrum security is the most senior piece of the capital structure that doesn't get repaid in full — it's the layer where the company's value runs out. Everything senior to it is money-good and gets paid at par; everything junior is out of the money and usually recovers little or nothing. Because the fulcrum is only partially impaired, it's typically the claim that converts into the new equity of the reorganized company, which is why it's so important. To find it, you take a view on enterprise value — say a distressed DCF or comparable multiples — and waterfall that value down by priority: first-lien, second-lien, unsecured bonds, and so on, subtracting claims until the value is exhausted. Whichever tranche the value 'breaks' in is the fulcrum. That's also why distressed funds try to buy it at a discount: own the fulcrum, and your debt claim converts into ownership and control when the company emerges. Note the fulcrum shifts with your valuation — mark enterprise value higher or lower and it can move up or down the stack.$ma$),

(1575, NULL, 'primary', 'Restructuring', 'Absolute Priority', 'core', 3, 'intern', 'Global',
 $q$Walk me through the absolute priority rule. Who gets paid, and in what order, in a Chapter 11?$q$,
 $kp$["Senior classes must be paid in full before any junior class recovers","Order: secured (to collateral value), then administrative and priority claims","Then general unsecured creditors (bonds, trade), then preferred equity","Common shareholders are last and usually wiped out in distress","Can be bent by consent or the narrow new-value exception","Cramdown enforces priority over a dissenting class"]$kp$::jsonb,
 $ma$The absolute priority rule says each class of claims must be paid in full before the next class down receives anything. So the waterfall runs: secured creditors first, up to the value of their collateral; then administrative and priority claims like DIP financing, professional fees, and certain taxes; then general unsecured creditors, meaning bondholders and trade creditors; then preferred equity; and finally common shareholders, who are last. In a genuinely distressed company the value usually runs out somewhere in the debt, so equity is typically wiped out — that's why shareholders often get nothing. The rule matters because it determines both recoveries and who ends up owning the company on exit. In practice it can be bent slightly — senior classes sometimes consent to give a junior class a small tip to avoid a fight, and there's a narrow new-value exception — but if a class objects, the court enforces priority through cramdown. So the order isn't academic; it's the backbone of every recovery analysis.$ma$),

(1576, NULL, 'primary', 'Restructuring', 'Liability Management', 'advanced', 4, 'associate', 'Global',
 $q$What is a liability management exercise? Walk me through an uptier and a drop-down, and why existing lenders hate them.$q$,
 $kp$["Out-of-court moves using credit-agreement flexibility to raise cash or cut leverage","Uptier: majority lenders issue new super-senior debt and subordinate the rest","Drop-down: collateral moved to an unrestricted sub, then pledged for new debt","Both exploit covenant gaps and required-lender mechanics","Non-participating lenders get primed or stripped of collateral (creditor-on-creditor violence)","J.Crew and Serta blockers now appear in newer credit docs to stop them"]$kp$::jsonb,
 $ma$A liability management exercise, or LME, is an out-of-court transaction that uses flexibility in the existing credit documents to raise new money or cut leverage without filing for bankruptcy. The two classic structures are uptiers and drop-downs. In an uptier, a majority group of lenders provides new super-priority debt and, in the same vote, amends the credit agreement to subordinate the lenders who weren't invited — the participating lenders jump ahead and the rest get pushed down. In a drop-down, the company moves valuable collateral — a brand, IP, a subsidiary — into an unrestricted subsidiary outside the lenders' security package, then raises new debt against it; that's the J.Crew playbook. Existing lenders hate both because they're 'creditor-on-creditor violence': you get primed or watch your collateral walk out the door while you're still a lender. These deals exploit gaps in the covenants and required-lender mechanics, so they routinely trigger litigation — and newer credit agreements now include explicit J.Crew and Serta blockers to stop them.$ma$),

(1577, NULL, 'primary', 'Restructuring', 'Distressed Valuation', 'advanced', 4, 'associate', 'Global',
 $q$How does valuing a distressed company differ from valuing a healthy one?$q$,
 $kp$["Assess both going-concern and liquidation value; recoveries anchor to the higher credible one","Use a higher, distress-adjusted discount rate","Normalize a depressed forecast; separate operational from balance-sheet distress","Probability-weight reorganization, sale, and liquidation scenarios","Pair valuation with the claims waterfall to see who receives the value","Watch NOLs, contingent liabilities, and the liquidity runway"]$kp$::jsonb,
 $ma$Valuing a distressed company is less about one clean DCF and more about a range of outcomes. First, going-concern versus liquidation: you estimate what the business is worth if it reorganizes and keeps operating, but also what creditors would recover in a wind-down, because recoveries anchor to whichever is higher and credible. Second, the discount rate is higher — more risk means a higher cost of capital. Third, you normalize the forecast: distressed near-term numbers are often depressed, and you have to separate genuine operational decline from pure balance-sheet distress, because a company can have a sound business but a broken capital structure. I'd probability-weight scenarios — reorganization, sale, or liquidation — rather than bet on a single base case. And valuation always pairs with the claims analysis: enterprise value matters, but who receives it depends on the waterfall. Finally I'd watch the items that swing value most — NOLs, contingent liabilities, and how much liquidity runway exists before the company runs out of cash.$ma$),

-- ============================== Capital Markets ==============================
(1578, NULL, 'primary', 'Capital Markets', 'ECM vs DCM', 'core', 2, 'intern', 'Global',
 $q$What's the difference between ECM and DCM, and what does each desk actually do day to day?$q$,
 $kp$["ECM raises equity: IPOs, follow-ons, convertibles, rights issues","DCM raises debt: bonds and sometimes loans, IG through high yield","Both sit between coverage bankers and the syndicate/trading desks","ECM advises on timing, valuation, structure, and equity demand","DCM advises on tenor, coupon, covenants, ratings, and market windows","Origination plus execution: build the book, price, allocate"]$kp$::jsonb,
 $ma$ECM and DCM are the two capital-raising desks. ECM, equity capital markets, helps companies raise equity — IPOs, follow-on offerings, convertibles, and rights issues. DCM, debt capital markets, helps them raise debt, mainly bonds and sometimes loans, from investment grade through high yield. Both sit between the coverage bankers, who own the client relationship, and the syndicate and trading desks, who place the paper with investors. On the ECM side, the day-to-day is advising on timing, valuation, structure, and reading equity demand — when to go public, how to position the story, how much dilution to accept. On the DCM side, it's advising on tenor, coupon, covenants, ratings strategy, and which market window gives the cheapest funding. In both cases the job is origination plus execution: win the mandate, then build the order book, price the deal, and allocate shares or bonds to investors. The simplest framing is that ECM raises ownership capital and DCM raises borrowed capital.$ma$),

(1579, NULL, 'primary', 'Capital Markets', 'Greenshoe / Stabilization', 'standard', 3, 'analyst', 'Global',
 $q$What is the greenshoe, or over-allotment option, and how do underwriters use it to stabilize a newly listed stock?$q$,
 $kp$["Lets underwriters sell up to ~15% more shares than the base deal","Created by over-allotting: the syndicate goes short the stock at pricing","Stock up: exercise the option, buy shares from the issuer at the offer price to cover","Stock down: cover by buying in the open market, supporting the price","Net effect stabilizes the aftermarket and flexes the deal to demand","Named after Green Shoe Manufacturing, the first issuer to use it"]$kp$::jsonb,
 $ma$The greenshoe, formally the over-allotment option, lets underwriters sell up to about 15% more shares than the base deal. The mechanic is that at pricing the bank over-allots — it sells those extra shares to investors, which leaves the syndicate short the stock. What happens next depends on trading. If the deal is hot and the stock rises, the underwriters exercise the greenshoe, buying the extra shares from the company at the offer price to cover the short — the company sells more, and the bank closes out cleanly. If the stock trades down, they instead cover by buying shares in the open market, and that buying supports the price exactly when it's weak. That's the stabilization function: the short position gives the syndicate a built-in reason to step in and buy a sagging new issue. So the greenshoe does two things — it lets the deal flex up to meet strong demand, and it gives underwriters a tool to smooth early trading. The name comes from Green Shoe Manufacturing, the first issuer to use it.$ma$),

(1580, NULL, 'primary', 'Capital Markets', 'Bond Pricing', 'core', 3, 'analyst', 'Global',
 $q$How is a corporate bond priced? Walk me through coupon, yield, and credit spread, and what moves the spread.$q$,
 $kp$["Price is the present value of coupons plus principal, discounted at the yield","Yield = risk-free benchmark (e.g., Treasury) plus a credit spread","Coupon set near par at issue; in the secondary market price and yield move inversely","Spread compensates for credit risk, structure, and liquidity","Spread widens on deterioration or risk-off, tightens on improvement or risk-on","Benchmarked against the issuer's curve and comparable bonds"]$kp$::jsonb,
 $ma$A corporate bond's price is the present value of its cash flows — the coupons plus principal at maturity — discounted at the bond's yield. The key relationship is that yield splits into two parts: the risk-free benchmark, like the matched-maturity Treasury, plus a credit spread that compensates for the issuer's default risk. At issuance you set the coupon so the bond prices near par given the required yield. After that, in the secondary market, the coupon is fixed, so price and yield move inversely — yields up, price down, and vice versa. The spread is where the credit work lives: it reflects the rating, leverage, sector, the bond's structure and covenants, and liquidity. Spreads widen when the credit deteriorates or markets turn risk-off, and tighten when fundamentals improve or risk appetite returns — so a bond can lose value either because Treasury rates moved or because its spread blew out. Pricing a new deal, we benchmark against the issuer's existing curve and comparable bonds from similar credits to land on a fair spread.$ma$),

(1581, NULL, 'primary', 'Capital Markets', 'Follow-on Offerings', 'advanced', 4, 'associate', 'Global',
 $q$What is a follow-on offering, and how does a marketed follow-on differ from an accelerated bookbuild and an ATM program?$q$,
 $kp$["Follow-on: a public company issues additional shares after its IPO","Marketed follow-on: roadshow/wall-cross over days, deeper price discovery","Accelerated bookbuild (block): priced overnight to institutions, fast, wider discount","ATM: dribble shares into the open market over time at prevailing prices","Trade-off is speed and certainty versus execution discount and market impact","Primary raises new capital; secondary is an existing holder selling down"]$kp$::jsonb,
 $ma$A follow-on is when an already-public company issues additional shares after its IPO. The three main routes differ mostly in speed and marketing. A marketed follow-on is the most involved — you wall-cross or run a short roadshow, market for a few days, and get deeper price discovery, which suits larger raises or a more complex story. An accelerated bookbuild, often called a block, skips most of the marketing: the bank builds the book overnight with institutions and prices by the next morning — fast and certain for the seller, but usually at a wider discount to the last close. An ATM, or at-the-market program, is the other extreme: instead of one block, the company dribbles shares into the open market over weeks at prevailing prices, minimizing impact but giving no certainty on size or timing. Cutting across all three is primary versus secondary — in a primary the company raises new capital, while in a secondary an existing holder sells down and the company gets nothing. Which route you pick comes down to size, speed, and how much discount you'll tolerate.$ma$),

(1582, NULL, 'primary', 'Capital Markets', 'Convertibles', 'advanced', 4, 'associate', 'Global',
 $q$Why would a company issue a convertible bond instead of straight debt or equity, and who buys converts?$q$,
 $kp$["A bond convertible into equity at a set price: straight debt plus an equity call option","Lower coupon than straight debt because investors pay for the option","Sells equity at a premium to today's price, reducing immediate dilution","Attractive for growth, high-volatility, or sub-IG issuers","Buyers: outright credit/equity funds and convertible-arb hedge funds","Downsides: dilution on conversion and added structural complexity"]$kp$::jsonb,
 $ma$A convertible bond is debt that can convert into equity at a preset conversion price, so it's really a straight bond plus an embedded equity call option. Companies issue them for a few reasons. First, the coupon is lower than on straight debt, because investors give up yield in exchange for the conversion option — cheap financing on a cash basis. Second, if it converts, the company has effectively sold equity at the conversion premium — a price above today's stock — so it's less dilutive than a follow-on at the current price. That makes converts attractive for growth names, high-volatility companies, or sub-investment-grade issuers who'd pay a steep coupon on straight high yield. On the buy side there are two groups: outright investors — credit and equity funds who like the asymmetric payoff of downside protection with equity upside — and convertible-arb hedge funds, who buy the bond and short the stock to isolate and trade the volatility. The trade-offs are real dilution if the stock runs through the conversion price, and a structure that's more complex to explain than plain debt or equity.$ma$),

(1583, NULL, 'primary', 'Capital Markets', 'Ratings / Crossover', 'advanced', 4, 'analyst', 'Global',
 $q$What role do the rating agencies play in a debt deal, and what happens to an issuer that gets downgraded from investment grade to high yield?$q$,
 $kp$["Agencies (Moody's, S&P, Fitch) rate default risk and shape the investor base","IG (BBB-/Baa3 and up) vs high yield below; the line gates demand","Rating drives coupon, spread, covenants, and who can hold the bond","Fallen angel: an IG-to-HY downgrade forces index-constrained selling","Spreads widen, funding costs rise, and some coupons step up on downgrade","Issuers manage to ratings to defend the investment-grade line"]$kp$::jsonb,
 $ma$The rating agencies — Moody's, S&P, and Fitch — assign credit ratings that act as a standardized proxy for default risk, and that rating shapes the whole deal: who can buy the bond, what coupon and spread the issuer pays, and how tight the covenants need to be. The critical line is between investment grade — BBB-/Baa3 and above — and high yield below it, because many investor mandates are gated on that threshold and simply can't hold sub-IG paper. So when an issuer is downgraded from IG to high yield, it becomes a 'fallen angel,' and the effect can be severe. Index- and mandate-constrained holders are forced to sell, pushing the spread wider and the price down — often before the actual downgrade, as the market anticipates it. The issuer's funding cost jumps, some bonds carry coupon step-ups triggered by a downgrade, and refinancing gets harder right when it's needed most. That's why companies near the line manage to their ratings — holding leverage to a target, keeping an active agency dialogue, and sometimes cutting buybacks or selling assets to defend the IG rating.$ma$) on conflict do nothing;
