-- Migration: expand thin categories (batch 2) — Due Diligence + Brainteaser
-- Date: 2026-06-24
--
-- Continues the gap-fill from 2026_20. Adds 12 primary questions (6 each) to the
-- next-thinnest categories: Due Diligence (18 -> 24) and Brainteaser (24 -> 30).
-- Authored around existing sets (535-1535 DD; 556-1545 Brainteaser) to avoid
-- topic overlap; difficulty kept inside each level's selector band. IDs 1584-1595.

insert into public.questions
  (id, parent_id, type, category, subtopic, importance, difficulty, candidate_level, region, question, key_points, model_answer)
values
-- ============================== Due Diligence ==============================
(1584, NULL, 'primary', 'Due Diligence', 'Commercial vs Financial DD', 'core', 2, 'intern', 'Global',
 $q$What is commercial due diligence, and how does it differ from financial due diligence?$q$,
 $kp$["Financial DD tests the numbers: quality of earnings, working capital, net debt, cash flow","Commercial DD tests the business: market size, growth, competitive position, customers","FDD is backward-looking and accounting-driven; CDD is forward-looking and market-driven","CDD relies on market research, customer interviews, and channel checks","Both feed the model: FDD normalizes the earnings base, CDD validates the growth plan","Run by different specialists (accountants vs strategy consultants) but must reconcile"]$kp$::jsonb,
 $ma$Financial and commercial due diligence answer two different questions. Financial DD tests the numbers — it's the accounting-driven workstream that validates quality of earnings, normalizes EBITDA for one-time items, checks working capital and net debt, and confirms the historical cash flow is real and sustainable. It's largely backward-looking: is the P&L you're buying actually what it claims to be? Commercial DD tests the business behind those numbers — the market size and growth, the competitive position, customer loyalty, and whether management's forward plan is credible. It's forward-looking and market-driven, and it leans on market research, customer and former-employee interviews, and channel checks rather than the company's ledgers. The two reconcile in the model: FDD gives you a clean, normalized earnings base to start from, and CDD tells you whether the growth assumptions layered on top are achievable. They're usually run by different specialists — accountants on the financial side, strategy consultants on the commercial side — but the deal team has to stitch them together, because a clean QoE on a business quietly losing its market is still a bad deal.$ma$),

(1585, NULL, 'primary', 'Due Diligence', 'Vendor Due Diligence', 'standard', 3, 'analyst', 'Global',
 $q$Walk me through a vendor, or sell-side, due diligence process. Why would a seller commission diligence on its own company?$q$,
 $kp$["Seller (via its bank and a DD firm) commissions independent DD before launching a sale","Produces a vendor DD report shared with vetted buyers in the data room","Lets the seller frame and pre-empt issues on its own terms","Levels the field across bidders, speeds the process, and supports price tension","Most common in competitive auctions, especially PE exits","Buyers still run confirmatory DD but lean on the VDD as a base"]$kp$::jsonb,
 $ma$Vendor due diligence is when the seller — usually through its investment bank and a diligence firm — commissions independent diligence on its own business before launching a sale, then shares that report with qualified buyers in the data room. The reason a seller pays for this is control and tension. By running quality-of-earnings and commercial work upfront, the seller gets to find and frame any issues on its own terms, rather than having a buyer 'discover' them mid-process and use them to chip the price. It also levels the playing field: every bidder starts from the same credible, third-party fact base, which keeps more buyers in the process longer and supports competitive tension on price. It speeds things up too, because buyers don't each have to rebuild the analysis from scratch. You see VDD most often in competitive auctions, particularly private equity exits, where the sponsor wants a clean, fast, high-certainty process. Buyers will still run their own confirmatory diligence — they won't outsource judgment to the seller's advisors — but they lean on the VDD report as the base and focus their own work on the areas they care most about.$ma$),

(1586, NULL, 'primary', 'Due Diligence', 'Carve-out DD', 'advanced', 4, 'associate', 'Global',
 $q$In a carve-out, what are stranded costs and transition services agreements (TSAs), and why do they matter to a buyer's model?$q$,
 $kp$["Carve-out: buying a division out of a larger parent, not a standalone company","Standalone costs: the unit needs its own IT, HR, finance that the parent used to provide","Stranded costs: parent-allocated costs that don't transfer cleanly, often understating the cost base","TSA: parent provides services to the unit temporarily post-close, for a fee","Buyer must model the true standalone cost base, not the carve-out P&L as presented","Mis-estimating dis-synergies inflates EBITDA and overstates the affordable price"]$kp$::jsonb,
 $ma$In a carve-out you're buying a division out of a larger parent, so the financials you get are not those of a standalone company — and that gap is where stranded costs and TSAs come in. While it sat inside the parent, the division shared functions like IT, HR, finance, procurement, and real estate. Once it's independent it needs its own versions of those, and the carve-out P&L rarely reflects the true standalone cost. Stranded costs are the flip side at the parent: costs that were allocated to the division but don't actually leave when it's sold, which can mean the carve-out's reported cost base is understated. A TSA, or transition services agreement, is the bridge: the parent agrees to keep providing certain services — running payroll, hosting systems — for a defined period after close, at a fee, while the buyer stands up its own capabilities. For the buyer's model this is critical: you have to build the real standalone cost base, layer in TSA fees during the transition, and estimate the one-time cost to separate. If you take the carve-out EBITDA at face value, you understate dis-synergies, overstate earnings, and overpay.$ma$),

(1587, NULL, 'primary', 'Due Diligence', 'Debt-like Items', 'standard', 3, 'analyst', 'Global',
 $q$How do you diligence a target's net debt at closing? Give examples of debt-like items buyers push to treat as debt.$q$,
 $kp$["Most deals are cash-free, debt-free: agree enterprise value, then bridge to equity value","Net debt = gross debt minus cash, but the fight is over what counts as debt","Debt-like items: unfunded pensions, deferred capex, earnouts, factoring, accrued bonuses","Also tax liabilities, restructuring provisions, capital leases, customer prepayments","Each item added reduces the equity value paid to the seller dollar-for-dollar","Comb the balance sheet and notes to surface them, then negotiate the definitions"]$kp$::jsonb,
 $ma$Most M&A deals are done on a cash-free, debt-free basis: you agree a price for the enterprise value, then bridge to the actual equity value the seller receives by subtracting net debt at closing. Net debt is gross debt minus cash, but in practice the real diligence — and the real negotiation — is over what counts as debt. Beyond obvious bank loans and bonds, buyers push to classify a range of 'debt-like items' as debt, because each one reduces the equity value they pay dollar-for-dollar. Classic examples are unfunded pension liabilities, deferred or underspent capex, accrued or unpaid bonuses, earnouts owed from prior deals, factored receivables, customer prepayments and deferred revenue, capital leases, and one-off liabilities like restructuring provisions or unpaid taxes. The seller, naturally, argues these are operating items or already captured in working capital. So the analyst's job in diligence is to comb the balance sheet and the notes to surface every candidate, quantify it, and hand the deal team a defensible list. Then it gets negotiated into the purchase agreement's definitions — because where you draw the debt-versus-working-capital line directly moves the final check.$ma$),

(1588, NULL, 'primary', 'Due Diligence', 'Synergy DD', 'advanced', 4, 'associate', 'Global',
 $q$Walk me through how you diligence cost versus revenue synergies in a strategic acquisition. Which would you actually underwrite?$q$,
 $kp$["Cost synergies (overlap, procurement, facilities) are more within the buyer's control","Revenue synergies (cross-sell, pricing, new markets) are higher value but lower probability","Underwrite cost synergies harder; haircut and phase revenue synergies heavily","Diligence bottom-up by line item, with named owners, timing, and cost-to-achieve","Net synergies = gross minus dis-synergies and cost-to-achieve","Don't pay synergies away in the price; they should accrue to the buyer"]$kp$::jsonb,
 $ma$When you diligence synergies you separate cost from revenue, because they have very different reliability. Cost synergies — eliminating overlapping functions, procurement scale, consolidating facilities and systems — are largely within the buyer's control, so you can underwrite them with more confidence. Revenue synergies — cross-selling each other's products, pricing improvements, entering new geographies — can be worth more but depend on customers behaving as hoped, so their probability is much lower. My rule of thumb is to underwrite cost synergies fairly hard, but bottom-up, and to haircut and back-end-load revenue synergies heavily, if I give them credit at all. The actual diligence is line-by-line: for each synergy you want a named owner, a timing profile, and the one-time cost to achieve it — you can't realize a procurement saving or a headcount reduction for free. Then net synergies are gross synergies minus dis-synergies and cost-to-achieve, phased over a realistic ramp. The point I'd make in an interview is that you have to be careful not to pay the full synergy value away in the purchase price — synergies are the buyer's to earn, and handing them to the seller upfront is exactly how acquirers overpay.$ma$),

(1589, NULL, 'primary', 'Due Diligence', 'People DD', 'standard', 3, 'analyst', 'Global',
 $q$What is key-person risk, and how would you diligence and mitigate it when acquiring a founder-led business?$q$,
 $kp$["Key-person risk: value concentrated in a founder or a few individuals who may leave","Diligence: relationships tied to the person, decision dependence, depth of the bench","Look at the org chart, tenure, equity ownership, and what breaks if they walk","Mitigate with retention packages, rollover/vesting equity, and non-competes","Lock in a transition period to hand over relationships post-close","Structure price to share the risk (earnout) rather than pay full value upfront"]$kp$::jsonb,
 $ma$Key-person risk is when a disproportionate share of a business's value sits with a founder or a small handful of people — the relationships, the technical know-how, or the decision-making all run through them — so the business could be impaired if they leave after the deal. In a founder-led company it's one of the first things I'd diligence. I'd map which customer and supplier relationships are personal to the founder, how much day-to-day decision-making depends on them, and how deep the management bench is beneath them — what actually breaks if they walk on day one. I'd look at the org chart, tenure, and how much equity, and therefore post-deal incentive, they hold. On mitigation, the tools are both structural and contractual: retention and incentive packages for key staff, requiring the founder to roll over equity and vest it over time, non-compete and non-solicit agreements, and a defined transition period where they stay on to hand over relationships. And critically, you can structure the price itself to share the risk — an earnout that pays the founder out over time and on performance, rather than handing them the full value upfront and hoping they stay engaged.$ma$),

-- ============================== Brainteaser ==============================
(1590, NULL, 'primary', 'Brainteaser', 'Probability', 'standard', 4, 'analyst', 'Global',
 $q$In a room of 23 people, what is roughly the probability that at least two share a birthday — and why is it so much higher than people expect?$q$,
 $kp$["Answer: about 50% with just 23 people","Compute via the complement: probability everyone has a distinct birthday","P(all distinct) = 365/365 x 364/365 x ... x 343/365, about 0.49","So P(at least one shared) is about 0.51","Intuition: count pairs, not people — 23 people make 253 pairs","Each pair matches with chance 1/365, and 253/365 is already large"]$kp$::jsonb,
 $ma$The surprising answer is about 50% — with just 23 people it's essentially a coin flip that two share a birthday. The clean way to compute it is the complement: instead of the messy 'at least one match,' find the probability that everyone has a distinct birthday and subtract from one. The first person can have any birthday, the second must avoid one day (364/365), the third must avoid two (363/365), and so on down to the 23rd avoiding 22 days (343/365). Multiply those together and you get about 0.49, so the chance of at least one shared birthday is roughly 1 minus 0.49, about 51%. The reason it feels too high is that people instinctively think about how many others share their own birthday — only 22 comparisons. But the question is about any pair matching, and 23 people form 23 times 22 over 2, which is 253 pairs. With 253 chances at a 1-in-365 match, a hit becomes more likely than not. The lesson is to count pairs, not people.$ma$),

(1591, NULL, 'primary', 'Brainteaser', 'Probability', 'standard', 3, 'intern', 'Global',
 $q$On average, how many times do you have to roll a fair die to get your first 6?$q$,
 $kp$["Answer: 6 rolls on average","Rolling a 6 is a success with probability p = 1/6 each roll","Trials until the first success follow a geometric distribution","Expected number of trials = 1/p = 6","Self-consistent check: E = 1 + (5/6)E solves to E = 6"]$kp$::jsonb,
 $ma$The answer is 6. Getting a 6 on a fair die is a success with probability one-sixth on each independent roll, and the number of rolls until your first success follows a geometric distribution. For a geometric distribution the expected number of trials until the first success is just 1 over the probability of success — so here it's 1 divided by one-sixth, which is 6. The intuition is simple: if something happens one time in six on average, you'll wait about six tries to see it. A quick way to prove the formula: let E be the expected number of rolls. With probability 1/6 you succeed on the first roll; with probability 5/6 you've used a roll and are back where you started, needing 1 plus E more. So E = 1 + (5/6)E, and solving that gives E = 6.$ma$),

(1592, NULL, 'primary', 'Brainteaser', 'Logic', 'standard', 4, 'analyst', 'Global',
 $q$You have 1,000 bottles of wine and exactly one is poisoned. A sip of the poison is fatal after 24 hours. You have 24 hours and a supply of rats. What is the minimum number of rats needed to guarantee identifying the poisoned bottle?$q$,
 $kp$["Answer: 10 rats","Treat each rat as one binary digit: drinks (1) or not (0)","Number the bottles 0-999 in binary; 2^10 = 1024 > 1000, so 10 bits suffice","Rat k drinks from every bottle with a 1 in bit position k","The pattern of which rats die spells the bottle number in binary","n rats distinguish 2^n bottles — logarithmic scaling"]$kp$::jsonb,
 $ma$The answer is 10 rats. The trick is to treat each rat as one binary digit. Number the bottles from 0 to 999 and write each number in binary — since 2 to the 10th is 1,024, which is more than 1,000, ten binary digits are enough to give every bottle a unique 10-bit code. Now assign one rat to each of the ten bit positions. Rat number k drinks a mixture from every bottle that has a 1 in the k-th position of its binary label. After 24 hours, look at which rats died. Each dead rat means the poisoned bottle had a 1 in that rat's position, and each surviving rat means a 0. Reading the dead-and-alive pattern across all ten rats spells out the poisoned bottle's number in binary. Because n rats produce 2-to-the-n distinguishable life-or-death patterns, ten rats cover up to 1,024 bottles — more than enough for 1,000. The general lesson is that one simultaneous test with binary encoding scales logarithmically: doubling the rats squares the number of bottles you can screen.$ma$),

(1593, NULL, 'primary', 'Brainteaser', 'Logic', 'standard', 4, 'associate', 'Global',
 $q$You have two identical eggs and a 100-floor building. An egg breaks if dropped from above some unknown floor and survives at or below it. What is the minimum number of drops that guarantees finding that floor in the worst case?$q$,
 $kp$["Answer: 14 drops in the worst case","Second egg, once the first breaks, must walk up one floor at a time","Make each successive first-egg jump one floor smaller to balance the worst case","Need n + (n-1) + ... + 1 = n(n+1)/2 >= 100","n = 14 gives 105 (clears 100); n = 13 gives only 91","Start at floor 14, then 27, then 39, and so on"]$kp$::jsonb,
 $ma$The answer is 14 drops in the worst case. The key insight is that the first egg narrows the range in big jumps, but once it breaks, the second egg has to walk up one floor at a time within the remaining gap — so you want to balance the worst case. If your first drop is from floor f and the egg breaks, the second egg must test the floors below it individually, costing up to f-1 more drops. To keep the total constant, each successive first-egg jump should be one floor smaller than the last. So you drop from floor n, then n + (n-1), then n + (n-1) + (n-2), and so on. You want that first jump n large enough that these shrinking steps still reach 100, which means n + (n-1) + ... + 1 = n(n+1)/2 must be at least 100. Solving, n = 14 gives 14 times 15 over 2, or 105, which clears 100, while 13 only reaches 91. So you start at floor 14, then 27, then 39, and so on — and wherever the breaking floor sits, you never exceed 14 total drops.$ma$),

(1594, NULL, 'primary', 'Brainteaser', 'Estimation', 'standard', 3, 'analyst', 'Global',
 $q$How many piano tuners are there in Chicago? Walk me through your reasoning.$q$,
 $kp$["Classic Fermi estimate; structure and assumptions matter more than the exact figure","Chicago metro ~ 9 million people at ~ 2.5 per household ~ 3.5 million households","Assume ~ 1 in 20 households has a piano tuned about once a year","Divide annual tunings by what one tuner does per year (~ 800)","Land on roughly 100-300 tuners","Flag the most sensitive assumption and sanity-check"]$kp$::jsonb,
 $ma$This is a classic Fermi problem, and the structure matters more than the exact number. Start with Chicago's metro population, roughly 9 million people, at about 2.5 people per household, so call it 3.5 million households. Suppose 1 in 20 households has a piano that actually gets tuned — that's about 175,000 pianos. If each is tuned roughly once a year, that's 175,000 tunings of demand per year. Now the supply side: a tuner might do 3 to 4 tunings a day and work maybe 200 to 250 days a year, so call it about 800 tunings per tuner per year. Dividing demand by capacity, 175,000 over 800 is roughly 220 tuners. So I'd estimate on the order of 100 to 300 piano tuners in Chicago, and I'd flag that the answer is most sensitive to the share of households with a tuned piano — push that from 1 in 20 to 1 in 40 and you halve the answer. The point is a structured estimate with explicit, debatable assumptions, not false precision.$ma$),

(1595, NULL, 'primary', 'Brainteaser', 'Probability', 'standard', 4, 'associate', 'Global',
 $q$I roll a fair die and tell you the result. You may either keep that many dollars or reroll once and take whatever the second roll shows. What is your strategy, and what is the expected value of the game?$q$,
 $kp$["Compare the first roll to a fresh roll's expected value of 3.5","Keep the first roll if it beats 3.5; reroll if below","So keep on 4, 5, 6; reroll on 1, 2, 3","EV = 1/2 x avg(4,5,6) + 1/2 x 3.5","= 1/2 x 5 + 1/2 x 3.5","Expected value = 4.25"]$kp$::jsonb,
 $ma$The strategy comes from comparing your first roll to what a fresh roll is worth on average. A single die roll has an expected value of (1+2+3+4+5+6)/6 = 3.5, so you should only reroll when your first roll is below 3.5 — that is, keep a 4, 5, or 6, and reroll on a 1, 2, or 3. To get the expected value of the game, split into those two cases. Half the time you roll a 4, 5, or 6 and keep it, and the average of those is (4+5+6)/3 = 5. The other half you roll a 1, 2, or 3, reroll, and get the fresh-roll expectation of 3.5. So the expected value is one-half times 5 plus one-half times 3.5, which is 2.5 plus 1.75, or 4.25. The intuition worth stating is that the option to reroll has value: it lifts the game from 3.5, a plain single roll, up to 4.25, precisely because you only exercise it when your first roll is below average.$ma$);
